---
- hosts: switches
  connection: local
  
  tasks:
  - name: run show version on remote devices
    exos_command:
      commands:
        - show version
        - show vlan
    register: output
   
  - name: Send notification message via Slack
    slack:
      token: TFNPHUU59/BHVTLCN5C/uv6TVCNIFkYMe9Ot2e3V2Se2
      msg: 'Status of Extreme Exos Switch on host {{ ansible_hostname }} is {{ output.stdout_lines }}' 
