---
- hosts: switches
  connection: local
  
  tasks:
  - name: run show version on remote devices
    exos_command:
      commands:
        - show version
    register: output
   
  - name: Send notification message via Slack
    slack:
      token: TFNPHUU59/BHVTLCN5C/u
      msg: 'Extreme Exos Switch output for version------> {{ output.stdout_lines }}'
  
  - name: run show version on remote devices
    exos_command:
      commands:
        - show vlan
    register: vlan

  - name: Send notification message via Slack
    slack:
      token: TFNPHUU59/BHVTLCN5C/u
      msg: 'Extreme Exos Switch output for vlan------>  {{ vlan.stdout_lines }}'
